More syntax fixing

diff --git a/.github/workflows/update-font.yml b/.github/workflows/update-font.yml
--- a/.github/workflows/update-font.yml
+++ b/.github/workflows/update-font.yml
@@ -27,11 +27,12 @@ jobs:
     runs-on: "ubuntu-latest"
     steps:
      - uses: actions/checkout@v3
-         run: |
-           if [[ $(wget -O - -o /dev/null https://raw.githubusercontent.com/matomo-org/matomo/$GITHUB_BASE_REF/plugins/Morpheus/stylesheets/base/icons.css | sed '4q;d') == $(sed>
-           then
-             echo "::error Font cachebuster paramater not updated see https://developer.matomo.org/guides/matomo-font"
-             exit 1
-           else
-            exit 0
-           fi
+     - name: Compare stylesheet to base branch
+       run: |
+         if [[ $(wget -O - -o /dev/null https://raw.githubusercontent.com/matomo-org/matomo/$GITHUB_BASE_REF/plugins/Morpheus/stylesheets/base/icons.css | sed '4q;d') == $(sed>
+         then
+           echo "::error Font cachebuster paramater not updated see https://developer.matomo.org/guides/matomo-font"
+           exit 1
+         else
+          exit 0
+         fi
